<form action="index" method="POST" id="frmAddSent" enctype="multipart/form-data">
	<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<!--tao tac hidden!-->
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>
				<?php echo $this->formHidden("hdnCode","",null); ?>
				<?php echo $this->formHidden("hdn_xml_tag_list","",null); ?>
				<?php echo $this->formHidden("hdn_xml_value_list","",null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList","",null); ?>
				<?php echo $this->formHidden("hdh_option",$this->option,null); ?>
				<?php echo $this->formHidden("hdn_object_id",$this->hdn_object_id,null); ?>
				<?php echo $this->formHidden("hdn_asset_id",$this->hdn_asset_id,null); ?>
				<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_table","",null); ?>					
				<?php echo $this->formHidden("hdn_pk","",null); ?>	
				<?php echo $this->formHidden("hdn_action",$this->action,null);?>
				<?php echo $this->formHidden("hdn_redirect","",null);?>			
				CẬP NHẬT THÔNG TIN BIẾN ĐỘNG TÀI SẢN			
			</td>
		</tr>
	</table><?php
	$urlCalendar = $this->urlCalendar; 
	$arrAsset = $this->arrAsset;
	$arrFluctuations = $this->arrFluctuations;?>	
	<div class="box container c1">
		<div class="pad">	
			<table cellpadding="0" cellspacing="0" width="98%" border="0">
				<col width="20%"/><col width="80%"/>
				<tr>
					<td class="normal_label"><b>Người đứng tên tài sản</b></td>
					<td class="normal_label"><b><?=$arrAsset[0]['C_REGISTER_USERNAME']?></b>&nbsp;</td>
				</tr>
				<tr>
					<td class="normal_label">Mã</td>
					<td class="normal_label"><?=$arrAsset[0]['C_CODE']?>&nbsp;</td>
				</tr>	
				<tr>
					<td class="normal_label">Tên</td>
					<td class="normal_label"><?=$arrAsset[0]['C_NAME']?>&nbsp;</td>
				</tr>	
				<tr>
					<td class="normal_label">Ngày bắt đầu sử dụng</td>
					<td class="normal_label"><?=$arrAsset[0]['C_BEGIN_DATE']?>&nbsp;</td>
				</tr>	
				<tr>
					<td class="normal_label">Ngày hết khấu hao</td>
					<td class="normal_label"><?=$arrAsset[0]['C_DEPRECIATION_DATE']?>&nbsp;</td>
				</tr>	
				<tr>
					<td class="normal_label">Tình trạng</td>
					<td class="normal_label">
						<?=Efy_Library ::_getNameByCode($this->arrStatus,$arrAsset[0]['C_STATUS'],'C_NAME')?>&nbsp;	
					</td>
				</tr>					
			</table>
		</div>
	</div>	
	<table width='98%'  border='0' cellspacing='0' cellpadding='0' align="center" class="normal_label">
		<col width="20%"><col width="80%">
		<tr><td style="height:20px;" colspan="2"><!--<hr width='100%' color='#' size='0'>--></td></tr>
		<tr width="100%">
			<td>
				Hình thức biến động:
			</td>
			<td>
				<div id="divLeaderID">
					<select id="C_WORK" name="C_WORK" option = "true" style="width:50%;" class="textbox normal_label" onchange="_showFluctuation(this);" message="Chua chon hinh thuc bien dong!">
						<option id="" name = "" value="">-- chọn hình thức biến động --</option><?php						
						$arrWorks = $this->arrWorks;						
						echo Efy_Library::_generateSelectOption($arrWorks,'C_CODE','C_CODE','C_NAME',$this->C_WORK);?>
					</select>	
				</div>
			</td>
		</tr>
		<tr width="100%">
				<td>
					Nội dung công việc:
				</td>
				<td>
					<textarea id="C_CONTENT" name="C_CONTENT" option="true" style="width:98%" class="normal_label" message="Ban phai cap nhat noi dung cong viec"></textarea>
				</td>
			</tr>
		<tr><td style="height:20px;" colspan="2"><!--<hr width='100%' color='#' size='0'>--></td></tr>
	</table>
	<div id="DIV_C_USE_INFO" style="display:none;">
		<table width='98%'  border='0' cellspacing='0' cellpadding='0' align="center" class="normal_label">
			<col width="20%"><col width="80%">	
			<tr width="100%">
			<td valign="middle">
				<label>Người sử dụng tài sản: </label>
			</td>
			<td>
				<table width='99%'  border='0' cellspacing='0' cellpadding='0' align="center" class="normal_label">
					<col width="80%"><col width="20%">
					<tr>
					<td valign="bottom">
						<select id="C_USE_INFO" name="C_USE_INFO" option = "true" style="width:50%;" class="textbox normal_label" message="Nguoi su dung tai san khong duoc de trong!">
							<option id="" name = "" value="">-- Chon nguoi su dung --</option><?php						
							$arr_all_staff = $_SESSION['arr_all_staff'];						
							echo Efy_Library::_generateSelectOption($arr_all_staff,'id','id','name',$arrResul[0]['C_REGISTER_USERID']);?>
						</select>
					
						<!--textarea class="textbox normal_textarea" readonly id="C_USE_INFO" style="width:100%;" optional = "true" rows="2" name="C_USE_INFO"><?=$arrResul[0]['C_USER_NAME_LIST']?></textarea>
						<input type="hidden" id="infor_invite" optional = "true" name="infor_invite" value="" xml_tag_in_db="infor_invite" xml_data="true"/>
					</td>
					<td align="left" valign="bottom" style="padding:0 0 0 20px;">
						<?=$this->formButton("btn_update","Chọn",array("type"=>"button","class"=>"add_large_button","onClick"=>"show_modal_dialog_onclick_update_unit_all('assets/assets/edit/showModelDialog/1',document.getElementById('infor_invite'),'".$this->brwName."'); getInforInvite();"))?>
					</td-->
					</td>
					</tr>
				</table>
			</td>
		</tr>
			<tr width="100%">
				<td>
					<label>Người đứng tên tài sản:
				</td>
				<td>
					<div id="divLeaderID">
						<select id="C_REGISTER_USERID" name="C_REGISTER_USERID" optional = "true" style="width:50%;" class="textbox normal_label" message="Nguoi dung ten tai san khong duoc de trong!">
							<option id="" name = "" value="">-- chọn người đứng tên --</option><?php						
							$arr_all_staff = $_SESSION['arr_all_staff'];						
							echo Efy_Library::_generateSelectOption($arr_all_staff,'id','id','name','');?>
						</select>	
					</div>
				</td>
			</tr>
		</table>
	</div>	
	<div id="DIV_C_VALUE" style="display:none;">
		<table width='98%'  border='0' cellspacing='0' cellpadding='0' align="center" class="normal_label">
			<col width="20%"><col width="80%">	
			<tr width="100%">
				<td>
					<label>Giá trị tài sản hiện tại:
				</td>
				<td>
					<input type="text" id="C_VALUE" name="C_VALUE" value="" class="normal_label" optional = "true" style="width:50%" message="Giá trị tai san khong duoc de trong!">
				</td>
			</tr>
		</table>
	</div>	
	<div id="DIV_C_STATUS" style="display:none;">
		<table width='98%'  border='0' cellspacing='0' cellpadding='0' align="center" class="normal_label">
			<col width="20%"><col width="80%">	
			<tr width="100%">
				<td>
					<label>Tình trạng tài sản:
				</td>
				<td>
					<select id="C_STATUS" name="C_STATUS" optional = "true" style="width:50%;" class="textbox normal_label">
						<option id="" name = "" value="">-- chọn tình trạng tài sản --</option><?php
						$arrStatus = $this->arrStatus;
						echo Efy_Library::_generateSelectOption($arrStatus,'C_CODE','C_CODE','C_NAME','');?>
					</select>
				</td>
			</tr>	
		</table>
	</div>		
	<div id="DIV_C_BEGIN_DATE" style="display:none;">
		<table width='98%'  border='0' cellspacing='0' cellpadding='0' align="center" class="normal_label">
			<col width="20%"><col width="80%">	
			<tr width="100%">
				<td>
					<label>Ngày bắt đầu sử dụng:
				</td>
				<td>
					<input class="textbox" style="width:10%" id ="C_BEGIN_DATE" name="C_BEGIN_DATE" value="" onchange="getNowYear(this);" onblur = 'this.value=DatePrompt(this)' type="text" isdate="true" optional = "true"  message="<?php echo "Ngay khong dung dinh dang ngay/thang/nam!";?>" onKeyDown="change_focus(document.forms[0],this)">
					<img src="<?= $this->baseUrl?>images/calendar.gif" border="0" onclick="DoCal('<?=$urlCalendar;?>',document.getElementById('C_BEGIN_DATE'));" style="cursor:pointer">	 						
				</td>
			</tr>	
		</table>
	</div>	
	<div id="DIV_C_DEPRECIATION_DATE" style="display:none;">
		<table width='98%'  border='0' cellspacing='0' cellpadding='0' align="center" class="normal_label">
			<col width="20%"><col width="80%">	
			<tr width="100%">
				<td>
					Thời gian hết khấu hao
				</td>
				<td>
					<input class="textbox" style="width:10%" id ="C_DEPRECIATION_DATE" name="C_DEPRECIATION_DATE" value="" onchange="getNowYear(this);" onblur = 'this.value=DatePrompt(this)' type="text" isdate="true" optional = "true"  message="<?php echo "Ngay khong dung dinh dang ngay/thang/nam!";?>" onKeyDown="change_focus(document.forms[0],this)">
					<img src="<?= $this->baseUrl?>images/calendar.gif" border="0" onclick="DoCal('<?=$urlCalendar;?>',document.getElementById('C_DEPRECIATION_DATE'));" style="cursor:pointer">	 						
				</td>
			</tr>	
		</table>
	</div>	
	<div id="DIV_ASSET_PARENT" style="display:none;">
		<table width='98%'  border='0' cellspacing='0' cellpadding='0' align="center" class="normal_label">
			<col width="20%"><col width="80%">	
			<tr width="100%">
				<td>
					<label>Thuộc tài sản:
				</td>
				<td>
					<select id="ASSET_PARENT" name="ASSET_PARENT" optional = "true" style="width:50%;" class="textbox normal_label">
						<option id="" name = "" value="">-- chọn tài sản --</option><?php
						$arrAssetParent = $this->arrAllAsset;
						echo Efy_Library::_generateSelectOption($arrAssetParent,'C_CODE','C_CODE','C_NAME','');?>
					</select>
				</td>
			</tr>	
		</table>
	</div>
	<table width='98%'  border='0' cellspacing='0' cellpadding='0' align="center" class="normal_label">
		<col width="20%"><col width="80%">	
		<tr style="width:100%">
			<td>
				<label>File đính kèm: </label>
			</td>
			<td>
				<?=$this->AttachFile;?>
			</td>
		</tr>
	</table>
	<!--Hien thi nut!-->			
	<table 	width='99%'  border='0' cellspacing='0' cellpadding='0' align="center" class="table_title">
		<tr><td style="height:20px;"><!--<hr width='100%' color='#3399FF' size='1'>--></td></tr>		
		<tr>
			<td align="center" style="padding-bottom:10px;">			
				<button name="btn_ghivathemmoi" id="btn_ghivathemmoi" type="button" class="add_large_button" onClick="actionUrl('fluctuations');document.getElementById('C_CONTENT').value = '';this.disabled=true;">Cập nhật</button>
				<?=$this->formsubmit('button','Quay lại',array("onClick"=>"actionUrl('index');","class"=>"add_large_button"))?>
			</td>
		</tr>			
	</table>
	<div>
	<table cellpadding="0" cellspacing="0" border="0" width="98%" align="center" class="list_table2" id="table1"><?php			
		$delimitor = $this->delimitor;//Lay ky tu phan cach giua cac phan tu
		//Hien thi cac cot cua bang hien thi du lieu
		$StrHeader = explode("!~~!",Efy_Library::_GenerateHeaderTable("3%" . $delimitor . "12%" . $delimitor . "20%" . $delimitor . "30%" . $delimitor . "15%" . $delimitor . "10%" . $delimitor . "10%"
										,$this->formCheckbox('all','', array('checked' => false,'onclick'=>'_checkedAll(this,document.getElementsByName(\'chk_item_id\'))')) . $delimitor . "Ngày" . $delimitor . "Công việc" . $delimitor . "Nội dung công việc" . $delimitor . "Người sử dụng" . $delimitor . "Giá trị" . $delimitor . "Tình trạng"
										,$delimitor));
		echo $StrHeader[0];				
		echo $StrHeader[1]; 		
		//Dinh nghia URL
		$sUrlEdit  = "viewrecord";
		$v_current_style_name = "round_row";			
		for($index = 0; $index < sizeof($arrFluctuations); $index++){				
			$documentId 	= $arrFluctuations[$index]['PK_VARIABLE_ASSETS'];
			$strFileName 	= $arrFluctuations[$index]['C_FILE_NAME'];
			$sFile = Efy_Library::_getAllFileAttach(substr($strFileName,0,-5),"@!~!@","!~!",$this->baseUrl . "attach-file/");
			if ($v_current_style_name == "odd_row"){
				$v_current_style_name = "round_row";
			}else{
				$v_current_style_name = "odd_row";					
			}?>						
			<tr class="<?=$v_current_style_name?>">	
				<td align="center" style="padding-left:3px;padding-right:3px;" class="normal_label">
					<input type="checkbox" id="chk_item_id" name="chk_item_id" value="<?=$documentId?>" optional="true">
				</td>
				<td align="center" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$documentId?>');" style="padding-left:3px;padding-right:3px;" class="normal_label">
					<?=$arrFluctuations[$index]['DATE']?>&nbsp;
				</td>								
				<!--Hien thi trich yeu!-->					
				<td onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$documentId?>');" style="padding-left:3px;padding-right:3px;" class="normal_label">
					<?=Efy_Library ::_getNameByCode($this->arrWorks,$arrFluctuations[$index]['C_WORK'],'C_NAME')?>&nbsp;
				</td>
				<!--Hien ket qua xu ly!-->	
				<td align="left" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$documentId?>');" align="left" style="padding-left:3px;padding-right:3px;" class="normal_label">
					<?=$arrFluctuations[$index]['C_CONTENT'] . " " . $sFile?>&nbsp;
				</td>
				<!--nguoi su dung!-->	
				<td align="left" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$documentId?>');" align="left" style="padding-left:3px;padding-right:3px;" class="normal_label">
					<?=$arrFluctuations[$index]['C_REGISTER_USERNAME']?>&nbsp;
				</td>	
				<td align="center" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$documentId?>');" align="left" style="padding-left:3px;padding-right:3px;" class="normal_label">
					<?=$arrFluctuations[$index]['C_VALUE']?>&nbsp;
				</td>
				<td onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$documentId?>');" align="left" style="padding-left:3px;padding-right:3px;" class="normal_label">
					<?=Efy_Library ::_getNameByCode($this->arrStatus,$arrFluctuations[$index]['C_STATUS'],'C_NAME')?>&nbsp;
				</td>
			</tr><?php							
		}
		if(sizeof($arrFluctuations) < 15){		
			echo Efy_Library::_addEmptyRow($this->iCountElement,15 -sizeof($arrFluctuations),$v_current_style_name,7);		
		}?>
	</table>	
	<table 	width='99%'  border='0' cellspacing='0' cellpadding='0' align="center" class="table_title">
		<tr>
			<td align="center" style="padding-bottom:10px;">			
				<input type="button" class="add_large_button" value="Xóa" onclick="btn_report_delete_onclick(document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id_list'),'T_VARIABLE_ASSETS','PK_VARIABLE_ASSETS','delete','fluctuations');">
				<?=$this->formsubmit('button','Quay lại',array("onClick"=>"actionUrl('index');","class"=>"add_large_button"))?>
			</td>
		</tr>			
	</table>
	</div>
</form>