<?php 
//$arrPermission = $_SESSION['arrStaffPermission'];
//if($arrPermission['CAP_NHAT_LOAI_DM'] || $arrPermission['CAP_NHAT_DM_DOI_TUONG'] || $arrPermission['CAP_NHAT_QUYEN'])
//{?>
<form action="index" method="POST" id="frmAddList">
	<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<!--tao tac hidden!-->
		<tr>
			<!--Sinh mot hidden luu ID loai danh muc!-->
			<?php echo $this->formHidden("hdn_id_listtype",$this->iIdListType,null); ?>	
			<!--Sinh mot hidden luu ID danh muc doi tuong!-->
			<?php echo $this->formHidden("hdn_list_id",$this->iIdList,null); ?>				
			<!--Bien hdn_xml_tag_list dung de luu danh sach cac THE XML tuong ung voi cac THUOC TINH cua mot doi tuong dang duoc cap nhat-->			
			<?php echo $this->formHidden("hdn_xml_tag_list",'',null); ?>			
			<!--Bien hdn_xml_value_list dung de luu danh sach cac gia tri cua cac THE XML tuong ung voi cac THUOC TINH cua mot doi tuong-->			
			<?php echo $this->formHidden("hdn_xml_value_list",'',null); ?>			
			<!--Sinh mot hidden luu list ID ma NSD chon!-->
			<?php echo $this->formHidden("hdn_object_id_list","",null); ?>	
			<!--Hidden luu gia tri cua list tag va list value (TagList|{*^*}|ValueList) -->
			<?php echo $this->formHidden("hdn_XmlTagValueList",$this->XmlTagValueList,null); ?>
			<!--Bien hdn_page dung de luu chi so trang hien thi hien thoi-->			
			<?php echo $this->formHidden("hdn_current_page",$this->currentPage,null); ?>	
			<!--Sinh mot hidden luu gia tri xac dinh so ban ghi / 1 trang!-->	
			<?php echo $this->formHidden("hdn_record_number_page",$this->numRowOnPage,null); ?>	
			<!--Bien hdn_filter_xml_tag_list dung de luu danh sach cac THE XML tuong ung voi cac tieu thuc loc tren giao dien DANH SACH DOI TUONG-->
			<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
			<!--Bien hdn_filter_xml_tag_list dung de luu gia tri cua cac THE XML tuong ung voi cac tieu thuc loc tren giao dien DANH SACH DOI TUONG-->	
			<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
		</tr>
	</table>
	<!--HIen thi tieu de man hinh danh sach!-->
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<?=$this->bodyTitle;?><br>				
			</td>
		</tr>
		<tr><td style="height:10px;"></td></tr>
	</table>
	<div id = "contentXml">
		<?php  echo $this->generateFormHtml;?>		
	</div>		
	<!--Hien thi nut!-->			
	<div id = "button">	
		<?=$this->formButton("btn_update","Cập nhật",array("type"=>"button","class"=>"add_large_button","onClick"=>"btn_save_list(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');"))?>								
		<?=$this->formsubmit('button','Quay lại',array("onClick"=>"actionUrl('index');","class"=>"add_large_button"))?>								
	</div>
</form>
<?php //} 
//else 
//	echo 'Bạn không có quyền truy cập chức năng này';
?>