
<table width="100%" cellpadding="0" cellspacing="0" align="center" height="35" class="footer_info_table" id="tbl_footer">
	<tr id="tr_footer">
		 <TD class="detail"><b><?php echo "Công ty Cổ phần Bạch Minh (Vega Corporation)"?></b><br><?php echo "Điện thoại: (84-4) 3 755 4190 - FAX: (84-4) 3 755 4190"?>&nbsp;&nbsp;&nbsp;
		Email: <a href="mailto:info@vega.com.vn "><?php echo "info@vega.com.vn "?></a>&nbsp;&nbsp;&nbsp;Website: <a href="http://www.vega.com.vn" target="_blank"><?php echo "http://www.vega.com.vn"?></a></TD>
		</tr>			
</table>	