<form action="index" method="POST" id="frmAddSent" enctype="multipart/form-data">	
	<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<!--tao tac hidden!-->
		<tr>
			<!--Sinh mot hidden luu list ID ma NSD chon!-->
			<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
			<!--Bien hdn_page dung de luu chi so trang hien thi hien thoi-->			
			<?php echo $this->formHidden("hdn_current_page",$this->currentPage,null); ?>	
			<!--Sinh mot hidden luu gia tri xac dinh so ban ghi / 1 trang!-->	
			<?php echo $this->formHidden("hdn_record_number_page",$this->numRowOnPage,null); ?>	
			<!--Bien hdn_filter_xml_tag_list dung de luu danh sach cac THE XML tuong ung voi cac tieu thuc loc tren giao dien DANH SACH DOI TUONG-->
			<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
			<!--Bien hdn_filter_xml_tag_list dung de luu gia tri cua cac THE XML tuong ung voi cac tieu thuc loc tren giao dien DANH SACH DOI TUONG-->	
			<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
			<!--Bien hdn_period_code dung de luu ma giai doan-->
			<?php echo $this->formHidden("hdn_asset_id",$this->hdn_asset_id,null); ?>
			<?php echo $this->formHidden("hdn_object_id",$this->hdn_object_id,null); ?>
		</tr>
	</table>	
	
	$urlCalendar = $this->urlCalendar; 
	$arrAsset = $this->arrAsset;
	$arrFluctuations = $this->arrFluctuations;?>
	
	<table width='98%'  border='0' cellspacing='0' cellpadding='0' align="center" class="normal_label">
		<col width="20%"><col width="80%">
		<tr><td style="height:20px;" colspan="2"><!--<hr width='100%' color='#' size='0'>--></td></tr>
		<tr width="100%">
				<td>
					Lý do từ chối:
				</td>
				<td>
					<textarea id="C_CONTENT" name="C_CONTENT" option="true" style="width:98%" class="normal_label" message="Ban phai cap nhat noi dung cong viec"></textarea>
				</td>
			</tr>
		<tr><td style="height:20px;" colspan="2"><!--<hr width='100%' color='#' size='0'>--></td></tr>
	</table>
	
	<!--Hien thi nut!-->			
	<table 	width='99%'  border='0' cellspacing='0' cellpadding='0' align="center" class="table_title">
		<tr><td style="height:20px;"><!--<hr width='100%' color='#3399FF' size='1'>--></td></tr>		
		<tr>
			<td align="center" style="padding-bottom:10px;">			
				<button name="btn_ghivathemmoi" id="btn_ghivathemmoi" type="button" class="add_large_button" onClick="actionUrl('fluctuations');document.getElementById('C_CONTENT').value = '';this.disabled=true;">Cập nhật</button>
				<?=$this->formsubmit('button','Quay lại',array("onClick"=>"actionUrl('index');","class"=>"add_large_button"))?>
			</td>
		</tr>			
	</table>
	
</form>
	