<form action="index" method="POST" id="frmSent">
<div><?php
	$urlCalendar = $this->urlCalendar;
	$arrAsset = $this->arrAsset; 
	$arrUser = $this->arrUser;
	$arrUserApproved = $this->arrUserApproved;
	$arrResul = $this->arrResult;?>
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<!--Cac doi tuong hidden tren form-->
				<?php echo $this->formHidden("hdn_current_page",$this->currentPage,null); ?>
				<?php echo $this->formHidden("cbo_nuber_record_page",$this->numRowOnPage,null); ?>
				<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
				<?php echo $this->formHidden("hdn_record_number_page",$this->numRowOnPage,null); ?>	
				<?php echo $this->formHidden("hdn_approved_status",$this->hdn_approved_status,null); ?>
				<?php echo $this->formHidden("hdn_object_id",$this->hdn_object_id,null); ?>
				<?php echo $this->formHidden("hdn_asset_id",$this->hdn_asset_id,null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList",$this->XmlTagValueList,null); ?>
				<!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->	
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>	
				<?php echo $this->formHidden("hdn_table","",null); ?>					
				<?php echo $this->formHidden("hdn_pk","",null); ?>	
				<?php echo $this->formHidden("hdn_redirect","",null);?>					
				<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>	
				<!--Bien hdnStatus dung de lay trang thai van ban tu menu trai ...-->	
				<?php echo $this->formHidden("hdnStatus","",null);?>
				<?php echo $this->formHidden("hdn_function_modul",$this->getModulLeft,null);?>
				
				<?php echo $this->formHidden("hdn_action",$this->action,null);?>
				<!--Cac doi tuong hidden tren form-->
				THÔNG TIN CHI TIẾT TÀI SẢN		
			</td>
		</tr>
	</table>
	<div class="box container c1">
		<div class="pad">	
			<table cellpadding="0" cellspacing="0" width="98%" border="0">
				<col width="20%"/><col width="80%"/>
				<tr>
					<td class="normal_label">Mã</td>
					<td class="normal_label"><?=$arrAsset[0]['C_CODE']?></td>
				</tr>	
				<tr>
					<td class="normal_label">Tên</td>
					<td class="normal_label"><?=$arrAsset[0]['C_NAME']?></td>
				</tr>	
				<tr>
					<td class="normal_label">Ngày bắt đầu sử dụng</td>
					<td class="normal_label"><?=$arrAsset[0]['C_BEGIN_DATE']?></td>
				</tr>	
				<tr>
					<td class="normal_label">Ngày hết khấu hao</td>
					<td class="normal_label"><?=$arrAsset[0]['C_DEPRECIATION_DATE']?></td>
				</tr>
				<tr>
					<td class="normal_label">Giá trị tài sản</td>
					<td class="normal_label"><?=$arrAsset[0]['C_VALUE']?></td>
				</tr>	
				<tr>
					<td class="normal_label">Tình trạng</td>
					<td class="normal_label">
						<?=Efy_Library ::_getNameByCode($this->arrStatus,$arrAsset[0]['C_STATUS'],'C_NAME')?>&nbsp;	
					</td>
				</tr>			
			</table>
		</div>
	</div><?
	if (sizeof($arrResul) >= 1){?>
	<div id="viewAllSentDocument">
		<div class="tieu_de">
			&nbsp;&nbsp;<b>THÀNH PHẦN TÀI SẢN</b>
		</div>
		<table cellpadding="0" cellspacing="0" border="0" width="98%" align="center" class="list_table2" id="table1"><?php			
			$delimitor = $this->delimitor;//Lay ky tu phan cach giua cac phan tu
			//Hien thi cac cot cua bang hien thi du lieu
			$StrHeader = explode("!~~!",Efy_Library::_GenerateHeaderTable("10%" . $delimitor . "40%" . $delimitor . "10%"  . $delimitor . "15%" . $delimitor . "15%" . $delimitor . "10%"
											,"Mã" . $delimitor . "Tên tài sản" . $delimitor . "Giá trị" . $delimitor . "Ngày sử dụng" . $delimitor . "Hết khấu hao" . $delimitor . "Tình trạng"
											,$delimitor));
			echo $StrHeader[0];				
			echo $StrHeader[1]; 		
			//Dinh nghia URL
			$sUrlEdit  = "addcomponent";
			$v_current_style_name = "round_row";			
			for($index = 0; $index < sizeof($arrResul); $index++){				
				$documentId = $arrResul[$index]['PK_SUB_ASSETS'];
				$strFileName 				= $arrResul[$index]['C_FILE_NAME'];
				$sFile = Efy_Library::_getAllFileAttach($strFileName,"@!~!@","!~!",$this->baseUrl . "attach-file/");
				if ($v_current_style_name == "odd_row"){
					$v_current_style_name = "round_row";
				}else{
					$v_current_style_name = "odd_row";					
				}?>						
				<tr class="<?=$v_current_style_name?>">	
					<td align="center" style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=$arrResul[$index]['C_CODE']?>&nbsp;
					</td>								
					<!--Hien thi trich yeu!-->					
					<td style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=$arrResul[$index]['C_NAME'] . " " . $sFile?>&nbsp;
					</td>
					<td style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=$arrResul[$index]['C_VALUE']?>&nbsp;
					</td>
					<!--Hien ket qua xu ly!-->	
					<td align="center" align="left" style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$arrResul[$index]['C_BEGIN_DATE']?>&nbsp;</td>	
					<td align="center" align="left" style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$arrResul[$index]['C_DEPRECIATION_DATE']?>&nbsp;</td>
					<td align="left" style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=Efy_Library ::_getNameByCode($this->arrStatus,$arrResul[$index]['C_STATUS'],'C_NAME')?>&nbsp;
					</td>
				</tr><?php					
			}
			if(sizeof($arrResul) < 5){		
				echo Efy_Library::_addEmptyRow($this->iCountElement,6 -sizeof($arrResul),$v_current_style_name,6);		
			}?>
		</table>		
	</div><?
	}?>
	<div id="viewAllSentDocument">
		<div class="tieu_de">
			&nbsp;&nbsp;<b>THÔNG TIN NGƯỜI SỬ DỤNG</b>
		</div>
		<table cellpadding="0" cellspacing="0" border="0" width="98%" align="center" class="list_table2" id="table1"><?php			
			$delimitor = $this->delimitor;//Lay ky tu phan cach giua cac phan tu
			//Hien thi cac cot cua bang hien thi du lieu
			$StrHeader = explode("!~~!",Efy_Library::_GenerateHeaderTable("5%" . $delimitor ."35%" . $delimitor . "15%" . $delimitor. "20%" . $delimitor. "25%" . $delimitor
											,"#" . $delimitor ."Nơi sử dụng" . $delimitor . "Ngày sử dụng". $delimitor . "Ngày đăng ký". $delimitor . "Trạng thái"
											,$delimitor));
			echo $StrHeader[0];				
			echo $StrHeader[1]; 		
			$v_current_style_name = "round_row";
			for($index = 0; $index < sizeof($arrUser); $index++){				
				if ($v_current_style_name == "odd_row"){
					$v_current_style_name = "round_row";
				}else{
					$v_current_style_name = "odd_row";					
				}?>						
				<tr class="<?=$v_current_style_name?>">	
					<td align="center" style="padding-left:3px;padding-right:3px;" class="normal_label">
						<input type="radio" id="chk_item_id" name="chk_item_id" value="<?=$arrUser[$index]['PK_USER_ASSETS']?>" optional="true" onclick="selectrow(this);">
					</td>				
					<td align="left" style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=$arrUser[$index]['C_NAME']?>&nbsp;
					</td>													
					<td style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=$arrUser[$index]['C_DATE_USE']?>&nbsp;
					</td>
					<td style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=$arrUser[$index]['C_DATE_REGISTER']?>&nbsp;
					</td>
					<td style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=Efy_Function_RecordFunctions::getNamStatus($arrUser[$index]['C_STATUS'])?>&nbsp;
					</td>
				</tr><?php					
			}
			if(sizeof($arrUser) < 5){		
				echo Efy_Library::_addEmptyRow($this->iCountElement,6 -sizeof($arrUser),$v_current_style_name,5);		
			}?>
		</table>		
	</div>
	<div align="center">
		<?=$this->formsubmit('button','Quay lại',array("onClick"=>"actionUrl('index');","class"=>"add_large_button"))?>
		<?php if($arrUserApproved[0]['FK_STAFF'] == $_SESSION['staff_id']){?>
			<input type="button" class="add_large_button" value="Duyệt cho mượn" onclick="document.getElementById('hdn_approved_status').value= '1';btn_update_onclick(document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'approved','1');">
			<input type="button" class="add_large_button" value="Từ chối" onclick="document.getElementById('hdn_approved_status').value = '0';btn_update_onclick(document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'approved','0');">
		<?php }?>
	</div>
</div>
</form>