<form action="index" method="POST" id="frmAddSent" enctype="multipart/form-data">
	<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<?=$this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>
				<?=$this->formHidden("hdn_deleted_new_file_id_list","",null); ?>
				<?=$this->formHidden("hdnCode","",null); ?>
				<?=$this->formHidden("hdn_xml_tag_list","",null); ?>
				<?=$this->formHidden("hdn_xml_value_list","",null); ?>
				<?=$this->formHidden("hdn_XmlTagValueList","",null); ?>
				<?=$this->formHidden("hdh_option",$this->option,null); ?>
				<?=$this->formHidden("hdn_object_id",$this->hdn_object_id,null);?>	
				<?=$this->formHidden("hdn_deleted_new_file_id_list","",null); ?>
				<?=$this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>	
				<?=$this->formHidden("hdnListId","",null); ?>	
				<?=$this->formHidden("number",'',null); ?>
				<?=$this->formHidden("hdnNhomChinh","",null);?>	
				<?=$this->formHidden("work_type", "", null);?>	
				CẬP NHẬT THÔNG TIN TÀI SẢN ĐĂNG KÝ MUA
			</td>
		</tr>
	</table><?php
	$urlCalendar = $this->urlCalendar; 
	$arrResul = $this->arrAsset;?>	
	<!--div style="text-align:right; width:99%;">
		<label>
			<a style="cursor:pointer;" onClick="btn_save_asset(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'add');">Cập nhật |</a>
			<a style="cursor:pointer;" onclick="actionUrl('index');">Quay lại</a>
		</label>
	</div-->
	<table width='99%'  border='0' cellspacing='0' cellpadding='0' align="center" class="normal_label">
		<col width="20%"><col width="80%">
		<tr width="100%">
			<td>
				<label>Loại tài sản:
			</td>
			<td>
				<div id="divLeaderID">
					<select id="C_TYPE" name="C_TYPE" optional = "true" style="width:50%;" class="textbox normal_label">
						<option id="" name = "" value="">-- chọn loại tài sản --</option><?php						
						$arrType = $this->arrType;						
						echo Efy_Library::_generateSelectOption($arrType,'C_CODE','C_CODE','C_NAME',$arrResul[0]['C_TYPE']);?>
					</select>	
				</div>
			</td>
		</tr>
		<tr width="100%">
			<td>
				<label>Nhóm tài sản:
			</td>
			<td>
				<select id="C_GROUP" name="C_GROUP" optional = "true" style="width:50%;" class="textbox normal_label">
					<option id="" name = "" value="">-- chọn nhóm tài sản --</option><?php
					$arrGroup = $this->arrGroup;
					echo Efy_Library::_generateSelectOption($arrGroup,'C_CODE','C_CODE','C_NAME',$arrResul[0]['C_GROUP']);?>
				</select>	
			</td>
		</tr>
		<!--tr width="100%">
			<td>
				<label>Mã tài sản:<font color="Red" size="2px;">*</font> </label>
			</td>
			<td>
				<input type="text" id="C_CODE" name="C_CODE" value="<?=$arrResul[0]['C_CODE']?>" class="normal_label" optional = "true" style="width:50%" message="Ma tai san khong duoc de trong!">
			</td>
		</tr-->
		<tr width="100%">
			<td>
				<label>Tên tài sản:<font color="Red" size="2px;">*</font> </label>
			</td>
			<td>
				<input type="text" id="C_NAME" name="C_NAME" value="<?=$arrResul[0]['C_NAME']?>" class="normal_label" option = "true" style="width:50%" message="Ten tai san khong duoc de trong!">
			</td>
		</tr>
		<tr width="100%">
			<td>
				<label>Thông tin về tài sản:<font color="Red" size="2px;">*</font> </label>
			</td>
			<td>
				<textarea class="textbox normal_textarea" id="C_INFO" style="width:99%;" option = "true" rows="2" name="C_INFO" message="Ban phai nhap vao thong tin ve tai san!"><?=$arrResul[0]['C_INFO']?></textarea>
			</td>
		</tr>
		<!--tr width="100%">
			<td>
				<label>Giá trị tài sản:
			</td>
			<td>
				<input type="text" id="C_VALUE" name="C_VALUE" value="<?=$arrResul[0]['C_VALUE']?>" class="normal_label" optional = "true" style="width:50%">
			</td>
		</tr>
		<tr width="100%">
			<td>
				<label>Tình trạng tài sản:
			</td>
			<td>
				<select id="C_STATUS" name="C_STATUS" optional = "true" style="width:50%;" class="textbox normal_label">
					<option id="" name = "" value="">-- chọn tình trạng tài sản --</option><?php
					$arrStatus = $this->arrStatus;
					echo Efy_Library::_generateSelectOption($arrStatus,'C_CODE','C_CODE','C_NAME',$arrResul[0]['C_STATUS']);?>
				</select>
			</td>
		</tr-->
		<tr width="100%">
			<td>
				<label>Ngày đăng ký:<font color="Red" size="2px;">*</font> </label>
			</td>
			<td>
				<input class="textbox" style="width:15%" id ="C_REGISTER_DATE" name="C_REGISTER_DATE" value="<?=$arrResul[0]['C_BEGIN_DATE']?>" onchange="getNowYear(this);" onblur = 'this.value=DatePrompt(this)' type="text" isdate="true" option = "true"  message="<?="Ngay khong dung dinh dang ngay/thang/nam!";?>">
				<img src="<?= $this->baseUrl?>images/calendar.gif" border="0" onclick="DoCal('<?=$urlCalendar;?>',document.getElementById('C_REGISTER_DATE'));" style="cursor:pointer">
			</td>
		</tr>
		<tr style="width:100%">
			<td>
				<label>Hình ảnh/File đính kèm: </label>
			</td>
			<td>
				<?=$this->AttachFile;?>
			</td>
		</tr>
		<!--tr width="100%">
			<td valign="middle">
				<label>Người sử dụng tài sản: </label>
			</td>
			<td>
				<table width='99%'  border='0' cellspacing='0' cellpadding='0' align="center" class="normal_label">
					<col width="80%"><col width="20%">
					<tr>
					<td valign="bottom">
						<textarea class="textbox normal_textarea" readonly id="C_USE_INFO" style="width:100%;" optional = "true" rows="2" name="C_USE_INFO"><?=$arrResul[0]['C_USER_NAME_LIST']?></textarea>
						<textarea style="width:99%; display:none;" class="normal_textarea" id="infor_invite" optional = "true" rows="3" name="infor_invite" xml_tag_in_db="infor_invite" xml_data="true" column_name="" message=""></textarea>
					</td>
					<td  align="left" valign="bottom" style="padding:0 0 0 20px;">
						<?=$this->formButton("btn_update","Chọn",array("type"=>"button","class"=>"add_large_button","onClick"=>"show_modal_dialog_onclick_update_unit_all('assets/assets/edit/showModelDialog/1',document.getElementById('infor_invite'),'".$this->brwName."'); getInforInvite();"))?>
					</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td>
				<label>Người đứng tên tài sản:<font color="Red" size="2px;">*</font> </label>
			</td>
			<td>
				<div id="divLeaderID">
					<select id="C_REGISTER_USERID" name="C_REGISTER_USERID" option = "true" style="width:50%;" class="textbox normal_label" message="Nguoi dung ten tai san khong duoc de trong!">
						<option id="" name = "" value="">-- Chọn người đứng tên --</option><?php						
						$arr_all_staff = $_SESSION['arr_all_staff'];						
						echo Efy_Library::_generateSelectOption($arr_all_staff,'id','id','name',$arrResul[0]['C_REGISTER_USERID']);?>
					</select>	
				</div>
			</td>
		</tr-->
		<tr width="100%">
			<td>
				<label>Lý do:<font color="Red" size="2px;">*</font> </label>
			</td>
			<td>
				<textarea class="textbox normal_textarea" id="ghi_chu" style="width:99%;" option = "true" rows="2" name="ghi_chu" xml_tag_in_db="ghi_chu" xml_data="true" message="Ban phai nhap vao ly do dang ky!"><?=$arrResul[0]['GHI_CHU']?></textarea>
			</td>
		</tr>
		<tr>
			<td>
				Trình duyệt:<font color="Red" size="2px;">*</font>
			</td>
			<td><?php
				$arrWorks = $this->arrWorks;
				$arr_all_staff = $_SESSION['arr_all_staff'];
				$count = sizeof($arr_all_staff);
				for($i =0; $i < sizeof($arrWorks); $i ++){					
					if($arrWorks[$i]['staff_process'] != ''){
						$staffId = $arrWorks[$i]['staff_process'];
						$staffName = Efy_Library ::_getItemAttrById($arr_all_staff, $staffId, 'name');
					}else{	
						for($j =0; $j < $count; $j ++){
							if($arr_all_staff[$j]['unit_id'] == $this->unitId && $arr_all_staff[$j]['position_code'] == $arrWorks[$i]['position_group']){
								$staffId = $arr_all_staff[$j]['id'];
								$staffName = Efy_Library ::_getItemAttrById($arr_all_staff, $staffId, 'name');
							}
						}
					}?>
					<div>
						<input onclick="document.getElementById('work_type').value = '<?=$arrWorks[$i]['C_CODE']?>';" type="radio" name="approve_id" option="true" value="<?=$staffId;?>" work_type="<?=$arrWorks[$i]['C_CODE']?>" message="Ban phai chon nguoi de trinh ky!"/><?=$arrWorks[$i]['C_NAME'] . '  - ' . $staffName;?>
					</div><?
				}?>		
			</td>
		</tr>
	</table>
	<!--Hien thi nut!-->			
	<table 	width='99%'  border='0' cellspacing='0' cellpadding='0' align="center" class="table_title">
		<tr>
			<td align="center" style="padding-bottom:10px;">			
				<button name="btn_ghivathemmoi" id="btn_ghivathemmoi" type="button" class="add_large_button" onClick="btn_save_asset(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'../../add/modul/<?=$this->modul?>');">Cập nhật</button>
				<?=$this->formsubmit('button','Quay lại',array("onClick"=>"actionUrl('../../index/modul/$this->modul');","class"=>"add_large_button"))?>
			</td>
		</tr>			
	</table>
	<div id="getSysbolforNowYear" style="display:none;"></div>
</form>