<form action="index" method="POST" id="frmSent">
<div><?php
	$urlCalendar = $this->urlCalendar;
	$arrAsset = $this->arrAsset;
	$arrWorks = $this->arrWorks;
	$arrProgress = $this->arrProgress;
	$arrResul = $this->arrResult;?>
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<!--Cac doi tuong hidden tren form-->
				<?php echo $this->formHidden("hdn_current_page",$this->currentPage,null); ?>
				<?php echo $this->formHidden("cbo_nuber_record_page",$this->numRowOnPage,null); ?>
				<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
				<?php echo $this->formHidden("hdn_record_number_page",$this->numRowOnPage,null); ?>	
				<?php echo $this->formHidden("hdn_object_id",$this->hdn_object_id,null); ?>
				<?php echo $this->formHidden("hdn_asset_id",$this->hdn_asset_id,null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList",$this->XmlTagValueList,null); ?>
				<!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->	
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>	
				<?php echo $this->formHidden("hdn_table","",null); ?>					
				<?php echo $this->formHidden("hdn_pk","",null); ?>	
				<?php echo $this->formHidden("hdn_redirect","",null);?>	
				<?=$this->formHidden("work_type", "", null);?>					
				<?=$this->formHidden("hdn_xml_tag_list","",null); ?>
				<?=$this->formHidden("hdn_xml_value_list","",null); ?>
				<?=$this->formHidden("hdn_XmlTagValueList","",null); ?>
				<!--Cac doi tuong hidden tren form-->
				THÔNG TIN TÀI SẢN		
			</td>
		</tr>
	</table>
	<div class="box container c1">
		<div class="pad">	
			<table cellpadding="0" cellspacing="0" width="98%" border="0">
				<col width="20%"/><col width="80%"/>
				<tr>
					<td class="normal_label">Tên tài sản</td>
					<td class="normal_label"><?=$arrAsset[0]['C_NAME']?></td>
				</tr>	
				<tr>
					<td class="normal_label">Ngày đăng ký</td>
					<td class="normal_label"><?=$arrAsset[0]['C_REGISTER_DATE']?></td>
				</tr>	
				<tr>
					<td class="normal_label">Mô tả</td>
					<td class="normal_label"><?=$arrAsset[0]['C_INFO']?></td>
				</tr>	
				<tr>
					<td class="normal_label">Lý do mua tài sản</td>
					<td class="normal_label"><?=$arrAsset[0]['GHI_CHU']?></td>
				</tr>		
			</table>
		</div>
	</div><?
	if (sizeof($arrProgress) >= 1){?>
	<div id="viewAllSentDocument">
		<div class="tieu_de">
			&nbsp;&nbsp;<b>NỘI DUNG CÔNG VIỆC</b>
		</div>
		<table cellpadding="0" cellspacing="0" border="0" width="98%" align="center" class="list_table2" id="table1"><?php			
			$delimitor = $this->delimitor;
			$StrHeader = explode("!~~!",Efy_Library::_GenerateHeaderTable("12%" . $delimitor . "20%" . $delimitor . "30%" . $delimitor . "38%"
											,"Ngày" . $delimitor . "Người thực hiện" . $delimitor . "Nội dung" . $delimitor . "Ghi chú"
											,$delimitor));
			echo $StrHeader[0];				
			echo $StrHeader[1]; 		
			//Dinh nghia URL
			$sUrlEdit  = "addcomponent";
			$v_current_style_name = "round_row";			
			for($index = 0; $index < sizeof($arrProgress); $index++){				
				if ($v_current_style_name == "odd_row"){
					$v_current_style_name = "round_row";
				}else{
					$v_current_style_name = "odd_row";					
				}?>						
				<tr class="<?=$v_current_style_name?>">	
					<td align="center" style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=$arrProgress[$index]['DATE']?>&nbsp;
					</td>					
					<td style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=Efy_Publib_Library ::_getItemAttrById($_SESSION['arr_all_staff'],$arrProgress[$index]['FK_STAFF'],'name')?>&nbsp;
					</td>
					<td style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=Efy_Publib_Library ::_getNameByCode($arrWorks,trim($arrProgress[$index]['C_WORK_TYPE']),'C_NAME');?>&nbsp;
					</td>
					<td align="left" style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=$arrProgress[$index]['C_CONTENT']?>&nbsp;
					</td>
				</tr><?php					
			}
			if(sizeof($arrResul) < 10){		
				echo Efy_Library::_addEmptyRow($this->iCountElement,6 -sizeof($arrResul),$v_current_style_name,4);		
			}?>
		</table>		
	</div><?
	}?>
	<div align="center">
		<?=$this->formsubmit('button','Quay lại',array("onClick"=>"actionUrl('../../index/modul/<?=$this->modul?>');","class"=>"add_large_button"))?>
	</div>
</div>
</form>